import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from "pdf-lib";
import { formatDateOnly, formatDateTime, toIsoDate } from "@/lib/format";
import { waiverParagraphs } from "@/lib/waiver";

/**
 * Renders a stored waiver into a self-contained PDF.
 *
 * Takes only persisted values, so the same record always produces the same document.
 * That is why nothing is cached: the copy attached to an email and the copy the owner
 * downloads months later are generated by this one function from the same snapshot.
 */

const PAGE_WIDTH = 612; // US Letter, in points.
const PAGE_HEIGHT = 792;
const MARGIN = 54;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

const BODY_SIZE = 9.5;
const BODY_LEADING = 13;
const HEADING_SIZE = 10.5;
const TITLE_SIZE = 14;
const META_SIZE = 8;

const INK = rgb(0.05, 0.05, 0.05);
const MUTED = rgb(0.42, 0.42, 0.42);
const RULE = rgb(0.75, 0.75, 0.75);

export type WaiverPdfInput = {
  student: { firstName: string; lastName: string; dateOfBirth: Date };
  waiver: {
    documentTitle: string;
    documentText: string;
    version: string;
    signerName: string;
    signerRole: "SELF" | "PARENT_GUARDIAN";
    signerRelationship: string | null;
    signerEmail: string;
    photoConsent: boolean;
    signatureImage: Uint8Array;
    signatureWidth: number;
    signatureHeight: number;
    signedAt: Date;
    ipAddress: string | null;
    userAgent: string | null;
  };
  organizationName: string;
};

/** Splits text to fit a column. pdf-lib has no automatic wrapping. */
function wrap(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const lines: string[] = [];
  for (const rawLine of text.split("\n")) {
    const words = rawLine.split(/\s+/).filter(Boolean);
    if (words.length === 0) {
      lines.push("");
      continue;
    }
    let line = "";
    for (const word of words) {
      const candidate = line ? `${line} ${word}` : word;
      if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
        line = candidate;
        continue;
      }
      if (line) lines.push(line);
      // A single word longer than the column (a long URL, say) has to be broken.
      if (font.widthOfTextAtSize(word, size) > maxWidth) {
        let chunk = "";
        for (const char of word) {
          if (font.widthOfTextAtSize(chunk + char, size) > maxWidth) {
            lines.push(chunk);
            chunk = char;
          } else {
            chunk += char;
          }
        }
        line = chunk;
      } else {
        line = word;
      }
    }
    if (line) lines.push(line);
  }
  return lines;
}

/**
 * Headings in the snapshot are plain text, so they are recognised by shape: a single
 * short line that does not end a sentence. Worst case a line renders bold that need
 * not be, which changes nothing about the wording on record.
 */
function isHeading(block: string): boolean {
  return !block.includes("\n") && block.length < 60 && !block.endsWith(".");
}

export async function renderWaiverPdf(input: WaiverPdfInput): Promise<Uint8Array> {
  const { student, waiver, organizationName } = input;

  const doc = await PDFDocument.create();
  doc.setTitle(`${waiver.documentTitle} — ${student.firstName} ${student.lastName}`);
  doc.setSubject(`Waiver version ${waiver.version}`);
  doc.setProducer(organizationName);
  doc.setCreationDate(waiver.signedAt);

  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page: PDFPage = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let cursor = PAGE_HEIGHT - MARGIN;

  /** Starts a new page when the next block would not fit above the bottom margin. */
  function ensureSpace(height: number) {
    if (cursor - height >= MARGIN) return;
    page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    cursor = PAGE_HEIGHT - MARGIN;
  }

  function drawLines(lines: string[], usedFont: PDFFont, size: number, leading: number) {
    for (const line of lines) {
      ensureSpace(leading);
      cursor -= leading;
      if (line) {
        page.drawText(line, { x: MARGIN, y: cursor, size, font: usedFont, color: INK });
      }
    }
  }

  function drawParagraph(text: string, usedFont: PDFFont, size: number, leading: number) {
    drawLines(wrap(text, usedFont, size, CONTENT_WIDTH), usedFont, size, leading);
  }

  // Header
  drawParagraph(organizationName.toUpperCase(), bold, META_SIZE, 11);
  cursor -= 4;
  drawParagraph(waiver.documentTitle, bold, TITLE_SIZE, TITLE_SIZE + 4);
  cursor -= 10;

  // Body: the stored snapshot, verbatim.
  const blocks = waiverParagraphs(waiver.documentText);
  for (const block of blocks) {
    // The snapshot repeats the title as its first block; the header already shows it.
    if (block === waiver.documentTitle.toUpperCase()) continue;

    if (isHeading(block)) {
      cursor -= 6;
      drawParagraph(block, bold, HEADING_SIZE, HEADING_SIZE + 3);
    } else {
      drawParagraph(block, font, BODY_SIZE, BODY_LEADING);
    }
    cursor -= 5;
  }

  // Signature block, kept together on one page rather than split across a break.
  const signatureImage = await doc.embedPng(waiver.signatureImage);
  const signatureWidth = 220;
  const aspect =
    waiver.signatureHeight > 0 && waiver.signatureWidth > 0
      ? waiver.signatureHeight / waiver.signatureWidth
      : 1 / 3;
  const signatureHeight = Math.min(signatureWidth * aspect, 90);

  const metaLines = [
    `Printed name: ${waiver.signerName}`,
    waiver.signerRole === "PARENT_GUARDIAN"
      ? `Signed by parent or legal guardian${waiver.signerRelationship ? ` (${waiver.signerRelationship})` : ""} on behalf of ${student.firstName} ${student.lastName}`
      : `Signed by the participant, ${student.firstName} ${student.lastName}`,
    `Participant date of birth: ${formatDateOnly(student.dateOfBirth)}`,
    `Email: ${waiver.signerEmail}`,
    `Signed: ${formatDateTime(waiver.signedAt)}`,
    `Photo and media consent: ${waiver.photoConsent ? "Granted" : "Not granted"}`,
    `Waiver version: ${waiver.version}`,
  ];

  ensureSpace(signatureHeight + metaLines.length * 11 + 60);
  cursor -= 18;
  page.drawText("SIGNATURE", { x: MARGIN, y: cursor, size: META_SIZE, font: bold, color: MUTED });
  cursor -= 6;

  cursor -= signatureHeight;
  page.drawImage(signatureImage, {
    x: MARGIN,
    y: cursor,
    width: signatureWidth,
    height: signatureHeight,
  });

  cursor -= 6;
  page.drawLine({
    start: { x: MARGIN, y: cursor },
    end: { x: MARGIN + 260, y: cursor },
    thickness: 0.75,
    color: RULE,
  });
  cursor -= 4;

  drawLines(metaLines, font, BODY_SIZE, 12);

  // Audit trail: evidence of how the signature was captured, not proof of identity.
  cursor -= 10;
  const auditLines = [
    `Recorded from IP address: ${waiver.ipAddress ?? "not recorded"}`,
    `Device: ${waiver.userAgent ?? "not recorded"}`,
  ];
  for (const line of auditLines) {
    for (const wrapped of wrap(line, font, META_SIZE, CONTENT_WIDTH)) {
      ensureSpace(10);
      cursor -= 10;
      page.drawText(wrapped, { x: MARGIN, y: cursor, size: META_SIZE, font, color: MUTED });
    }
  }

  // Page numbers, added last so the total is known.
  const pages = doc.getPages();
  pages.forEach((p, index) => {
    const label = `Page ${index + 1} of ${pages.length}`;
    p.drawText(label, {
      x: PAGE_WIDTH - MARGIN - font.widthOfTextAtSize(label, META_SIZE),
      y: MARGIN - 24,
      size: META_SIZE,
      font,
      color: MUTED,
    });
  });

  return doc.save();
}

/** Stable, human-readable filename for downloads and email attachments. */
export function waiverFileName(student: { lastName: string; firstName: string }, signedAt: Date) {
  const slug = `${student.lastName}-${student.firstName}`
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return `waiver-${slug || "student"}-${toIsoDate(signedAt)}.pdf`;
}
